name: jupyter
channels:
  - etetoolkit
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - ete3=3.1.2
  - jupyter=1.0.0
  - nbconvert=6.0.6
  - pandas=0.25.2
  - python=3.6.8
  - seaborn=0.9.0
